version: "3.7"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: inventory
      INVENTORY_FILE: ./inventory.json
      PRODUCTS_FILE: ./products.json
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
    expose:
      - "3306"
    volumes:
      - "./db/schema.sql:/docker-entrypoint-initdb.d/1.sql"